# Generated by Django 6.0.4 on 2026-08-22 05:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='A short, factual introduction. Do not add unverified credentials.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Arya Skin Clinic', max_length=100)),
                ('doctor_name', models.CharField(default='Dr. Naresh Rathod', max_length=100)),
                ('professional_title', models.CharField(default='Dermatologist', max_length=120)),
                ('location_summary', models.CharField(default='Pratap Nagar | Chaksu | Jaipur', help_text='A short display summary, not a substitute for clinic addresses.', max_length=180)),
                ('primary_phone', models.CharField(blank=True, help_text='Verified site-wide fallback only. Prefer branch-specific numbers.', max_length=30)),
                ('default_whatsapp', models.CharField(blank=True, help_text='Verified site-wide fallback only. Prefer branch-specific numbers.', max_length=30)),
                ('default_email', models.EmailField(blank=True, max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('medical_disclaimer', models.TextField(default='This information is intended for general educational purposes and does not replace consultation with a qualified medical professional.')),
                ('google_analytics_id', models.CharField(blank=True, max_length=30)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=30)),
                ('default_social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
