# Generated by Django 6.0.4 on 2026-08-22 06:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('website', '0003_reframe_site_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('image', 7), ('image_text', 11), ('quote', 14), ('faq', 19), ('call_to_action', 24), ('doctor_advice', 26), ('information', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link'], 'template': 'blocks/rich_text.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the meaningful content of the image.', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image left'), ('right', 'Image right')]}), 11: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 8), ('heading', 0), ('text', 9), ('image_position', 10)]], {}), 12: ('wagtail.blocks.TextBlock', (), {'max_length': 500}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('quote', 12), ('attribution', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 160}), 16: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link']}), 17: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'max_num': 12, 'min_num': 1}), 19: ('wagtail.blocks.StructBlock', [[('heading', 15), ('items', 18)]], {}), 20: ('wagtail.blocks.TextBlock', (), {'max_length': 400, 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 22: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.URLBlock', (), {'required': False}), 24: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 20), ('label', 21), ('internal_page', 22), ('external_url', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': "Doctor's advice", 'max_length': 160}), 26: ('wagtail.blocks.StructBlock', [[('heading', 25), ('text', 16)]], {}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('information', 'Information'), ('warning', 'Warning')]}), 28: ('wagtail.blocks.StructBlock', [[('style', 27), ('heading', 0), ('text', 16)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('image', 7), ('image_text', 11), ('quote', 14), ('faq', 19), ('call_to_action', 24), ('doctor_advice', 26), ('information', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link'], 'template': 'blocks/rich_text.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the meaningful content of the image.', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image left'), ('right', 'Image right')]}), 11: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 8), ('heading', 0), ('text', 9), ('image_position', 10)]], {}), 12: ('wagtail.blocks.TextBlock', (), {'max_length': 500}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('quote', 12), ('attribution', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 160}), 16: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link']}), 17: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'max_num': 12, 'min_num': 1}), 19: ('wagtail.blocks.StructBlock', [[('heading', 15), ('items', 18)]], {}), 20: ('wagtail.blocks.TextBlock', (), {'max_length': 400, 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 22: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.URLBlock', (), {'required': False}), 24: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 20), ('label', 21), ('internal_page', 22), ('external_url', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': "Doctor's advice", 'max_length': 160}), 26: ('wagtail.blocks.StructBlock', [[('heading', 25), ('text', 16)]], {}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('information', 'Information'), ('warning', 'Warning')]}), 28: ('wagtail.blocks.StructBlock', [[('style', 27), ('heading', 0), ('text', 16)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clinic_section_heading',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concerns_heading',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='doctor_section_heading',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_heading',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_heading',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='HomePageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', wagtail.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
