# Generated by Django 6.0.4 on 2026-08-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_seed_milestone_2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blog_section_heading',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
