# Generated by Django 6.0.4 on 2026-08-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_homepage_blog_section_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='analytics_enabled',
            field=models.BooleanField(default=False, help_text='Enable only after account ownership, the privacy notice, consent behavior, and the analytics configuration have been approved.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_search_console_verification',
            field=models.CharField(blank=True, help_text="Content value from Google's HTML verification meta tag. Do not paste the complete tag.", max_length=255),
        ),
    ]
