# Generated by Django 6.0.4 on 2026-08-23 05:44

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0007_sitesettings_analytics_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterGalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Optional factual introduction. Do not promise results or identify a patient.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BeforeAfterGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Use a neutral description; do not include a patient name.', max_length=160)),
                ('before_alt_text', models.CharField(help_text='Describe only what is visibly relevant in the before image.', max_length=255)),
                ('after_alt_text', models.CharField(help_text='Describe only what is visibly relevant in the after image.', max_length=255)),
                ('caption', models.TextField(blank=True, help_text='Optional verified context. Do not identify a patient, promise a result, or add an unverified treatment or time claim.', max_length=500)),
                ('publication_consent_confirmed', models.BooleanField(default=False, help_text='Confirm that documented consent specifically permits public website publication. Do not upload the consent document here.')),
                ('presentation_reviewed', models.BooleanField(default=False, help_text='Confirm that both images show the same person, labels are accurate, and cropping or editing does not create a misleading comparison.')),
                ('after_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('before_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='website.beforeaftergallerypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
