# Generated by Django 6.0.4 on 2026-08-23 05:44

from django.db import migrations


def seed_before_after_gallery(apps, schema_editor):
    from django.contrib.contenttypes.models import ContentType
    from wagtail.models import Page

    BeforeAfterGalleryPage = apps.get_model(
        "website", "BeforeAfterGalleryPage"
    )
    HomePage = apps.get_model("website", "HomePage")

    home_record = HomePage.objects.first()
    if not home_record or BeforeAfterGalleryPage.objects.exists():
        return

    home = Page.objects.get(pk=home_record.pk)
    content_type = ContentType.objects.get_or_create(
        app_label="website",
        model="beforeaftergallerypage",
    )[0]
    page = BeforeAfterGalleryPage(
        title="Before and after",
        slug="before-after",
        show_in_menus=True,
        live=False,
        has_unpublished_changes=True,
        content_type_id=content_type.pk,
        locale_id=home.locale_id,
        url_path=f"{home.url_path}before-after/",
    )
    home.add_child(instance=page)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_beforeaftergallerypage_beforeaftergalleryitem'),
    ]

    operations = [
        migrations.RunPython(
            seed_before_after_gallery,
            migrations.RunPython.noop,
        ),
    ]
