# Generated by Django 6.0.4 on 2026-09-07 09:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0009_seed_before_after_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllustratedCareJourneyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Optional educational introduction. Do not describe the illustrations as patient results or predict an outcome.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IllustratedCareJourneyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Use a neutral visible-change description, not a treatment claim.', max_length=160)),
                ('before_alt_text', models.CharField(help_text='Describe only what is visibly relevant in the first illustration.', max_length=255)),
                ('after_alt_text', models.CharField(help_text='Describe only what is visibly relevant in the second illustration.', max_length=255)),
                ('caption', models.TextField(blank=True, help_text='Use neutral educational context. Do not name a treatment, time interval, typical result, or diagnosis.', max_length=500)),
                ('illustration_disclosure_confirmed', models.BooleanField(default=False, help_text='Confirm that both images are synthetic illustrations and the page does not present them as patient photographs or clinical evidence.')),
                ('presentation_reviewed', models.BooleanField(default=False, help_text='Confirm clinical reasonableness and that identity, crop, lighting, colour, and labels create a fair, non-exaggerated comparison.')),
                ('after_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('before_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='website.illustratedcarejourneypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
