# Generated by Django 6.0.4 on 2026-08-22 05:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicpage',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_pages', to='doctors.doctorpage'),
        ),
        migrations.AddField(
            model_name='clinicopeninghours',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='clinics.clinicpage'),
        ),
        migrations.AddField(
            model_name='clinicimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='clinics.clinicpage'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinicpage'),
        ),
    ]
