# Generated by Django 6.0.4 on 2026-08-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_seed_doctor_and_clinics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicpage',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Use a verified international number beginning with +.', max_length=30),
        ),
    ]
