# Generated by Django 6.0.4 on 2026-08-22 06:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_alter_clinicpage_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('clinic_name', models.CharField(editable=False, help_text='Snapshot retained if the editorial clinic page is later removed.', max_length=255)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits and optional +, spaces, or hyphens.', regex='^\\+?[0-9 ()-]{7,24}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_date', models.DateField()),
                ('time_preference', models.CharField(choices=[('no_preference', 'No preference'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='no_preference', max_length=20)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('consent_version', models.CharField(editable=False, max_length=40)),
                ('source_path', models.CharField(blank=True, editable=False, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('staff_note', models.TextField(blank=True, help_text='Administrative follow-up only. Do not store diagnosis or detailed clinical notes here.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_enquiries', to='clinics.clinicpage')),
            ],
            options={
                'verbose_name': 'appointment enquiry',
                'verbose_name_plural': 'appointment enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
