# Generated by Django 6.0.4 on 2026-08-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentenquiry',
            name='staff_note',
            field=models.TextField(blank=True, help_text='Administrative follow-up only. Do not store diagnosis or detailed clinical notes here.', max_length=1000),
        ),
    ]
