# Generated by Django 6.0.4 on 2026-09-03 05:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointmentenquiry_staff_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('retrying', 'Retrying'), ('sent', 'Sent')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_type', models.CharField(blank=True, editable=False, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='appointments.appointmentenquiry')),
            ],
            options={
                'verbose_name': 'appointment notification delivery',
                'verbose_name_plural': 'appointment notification deliveries',
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('enquiry', 'recipient'), name='unique_appointment_notification_recipient')],
            },
        ),
    ]
